DROP TABLE IF EXISTS ESTUDANTES;
CREATE TABLE ESTUDANTES (id varchar(255) primary key, NOME varchar(255), SOBRENOME varchar(255));

DROP TABLE IF EXISTS SUBJECTS;
CREATE TABLE SUBJECTS (id int auto_increment primary key, name varchar(255));

DROP TABLE IF EXISTS AIRPLANE;
CREATE TABLE AIRPLANE (
id INT PRIMARY KEY,
brand VARCHAR(60),
model VARCHAR(60),
registration INT,
dateEntryIntoService DATE);
