version: '3.8'
services:
  market-store:
    image: marketstore
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: marketplace
      # IF DATABASE DOES NOT EXISTS, EXECUTE THE FOLLOWING COMMANDS:

      # volumes:
      #- ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  mongodb:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      MONGO_HOST: mongo-db
      MONGO_PORT: 27017
      MONGO_DB: marketplace